# Stubs for fbsp_pb2 (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, List, Dict

DESCRIPTOR: Any
DataHandlerType: Any
ServiceHandlerType: Any
State: Any
NONE: int
B_PROVIDER: int
B_CONSUMER: int
C_PROVIDER: int
C_CONSUMER: int
PUBLISHER: int
SUBSCRIBER: int
FAN_IN: int
FAN_OUT: int
ILLEGAL: int
PROVIDER: int
CONSUMER: int
UNKNOWN: int
READY: int
RUNNING: int
WAITING: int
SUSPENDED: int
FINISHED: int
ABORTED: int
CREATED: int
BLOCKED: int
STOPPED: int
ProtocolDescription: Any
ProtocolDescription.uid: bytes
ProtocolDescription.version: str
ProtocolDescription.level: int
ProtocolDescription.supports: List[str]
PlatformId: Any
PlatformId.uid: bytes
PlatformId.version: str
VendorId: Any
VendorId.uid: bytes
AgentIdentification: Any
AgentIdentification.uid: bytes
AgentIdentification.name: str
AgentIdentification.version: str
AgentIdentification.fbsp: ProtocolDescription
AgentIdentification.protocol: ProtocolDescription
AgentIdentification.vendor: VendorId
AgentIdentification.platform: PlatformId
AgentIdentification.classification: str
PeerIdentification: Any
PeerIdentification.uid: bytes
PeerIdentification.host: str
PeerIdentification.pid: int
PeerIdentification.identity: AgentIdentification
PeerIdentification.supplement: List[Any]
ErrorDescription: Any
ErrorDescription.code: int
ErrorDescription.description: str
ErrorDescription.context: Dict[Any, Any]
ErrorDescription.annotation: Dict[Any, Any]
CancelRequests: Any
CancelRequests.token: bytes
CancelRequests.supplement: List[Any]
StateInformation: Any
StateInformation.state: int
StateInformation.supplement: List[Any]
ServiceAbility: Any
ServiceAbility.service_type: int
ServiceAbility.data_handler: List[int]
ServiceAbility.protocol: List[ProtocolDescription]
ServiceAbility.supplement: List[Any]
ReplySvcAbilities: Any
ReplySvcAbilities.can_repeat_message: int
ReplySvcAbilities.service_state: ProtocolDescription
ReplySvcAbilities.service_config: ProtocolDescription
ReplySvcAbilities.service_control: ProtocolDescription
ReplySvcAbilities.abilities: Dict[str, ServiceAbility]
ReqestConRepeat: Any
ReqestConRepeat.last: int
